version: '2'
services:
  mariadb:
    mem_limit: 3072m
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - data:/var/lib/mysql/
    ports:
      - 3306:3306
    command: --innodb-buffer-pool-size=2G --character-set-server=utf8 --collation-server=utf8_swedish_ci

volumes:
  data: